
import java.util.ArrayList;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author andgz
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        jpcrud.setSize(423, 335);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frameCrud = new javax.swing.JFrame();
        jpcrud = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tabs = new javax.swing.JTabbedPane();
        jpAgregarEsc = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jtIP = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtmask = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jthostname = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jtram = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jtcapalm = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        btHDD = new javax.swing.JRadioButton();
        btSSD = new javax.swing.JRadioButton();
        btGraphics = new javax.swing.JCheckBox();
        btagregarEsc = new javax.swing.JButton();
        AgregarLaptop = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jtIP2 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jtmask2 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jthostname2 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jtmarca = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtdefinicion = new javax.swing.JTextField();
        rgbbox = new javax.swing.JCheckBox();
        agregarLaptop = new javax.swing.JButton();
        jpListar = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listPC = new javax.swing.JTextArea();
        jpEliminar = new javax.swing.JPanel();
        crudSalir = new javax.swing.JButton();
        almacenamiento = new javax.swing.ButtonGroup();
        bgPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btcrud = new javax.swing.JButton();
        btingrese = new javax.swing.JButton();

        frameCrud.setFocusable(false);
        frameCrud.setFocusableWindowState(false);

        jpcrud.setBackground(new java.awt.Color(102, 102, 255));

        jLabel2.setBackground(new java.awt.Color(51, 51, 51));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("CRUD");

        tabs.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tabsStateChanged(evt);
            }
        });

        jLabel3.setText("IP");

        jLabel4.setText("Mask");

        jLabel5.setText("Hostname");

        jLabel9.setText("RAM");

        jLabel10.setText("Capacidad de almacenamiento");

        jLabel11.setText("Tipo de almacenamiento: ");

        almacenamiento.add(btHDD);
        btHDD.setText("HDD");
        btHDD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHDDActionPerformed(evt);
            }
        });

        almacenamiento.add(btSSD);
        btSSD.setText("SSD");

        btGraphics.setText("Tarjeta grafica");

        btagregarEsc.setBackground(new java.awt.Color(102, 255, 102));
        btagregarEsc.setText("Agregar");
        btagregarEsc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btagregarEscActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpAgregarEscLayout = new javax.swing.GroupLayout(jpAgregarEsc);
        jpAgregarEsc.setLayout(jpAgregarEscLayout);
        jpAgregarEscLayout.setHorizontalGroup(
            jpAgregarEscLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAgregarEscLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpAgregarEscLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpAgregarEscLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(47, 47, 47)
                        .addComponent(jtram, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpAgregarEscLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jthostname, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpAgregarEscLayout.createSequentialGroup()
                        .addGroup(jpAgregarEscLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jpAgregarEscLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtmask, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtIP, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(26, 26, 26)
                .addGroup(jpAgregarEscLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpAgregarEscLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel11)
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jpAgregarEscLayout.createSequentialGroup()
                            .addComponent(btHDD)
                            .addGap(27, 27, 27)
                            .addComponent(btSSD))
                        .addComponent(jtcapalm))
                    .addComponent(btGraphics))
                .addContainerGap(49, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpAgregarEscLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btagregarEsc)
                .addGap(175, 175, 175))
        );
        jpAgregarEscLayout.setVerticalGroup(
            jpAgregarEscLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAgregarEscLayout.createSequentialGroup()
                .addGroup(jpAgregarEscLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpAgregarEscLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel10))
                    .addGroup(jpAgregarEscLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jpAgregarEscLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpAgregarEscLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpAgregarEscLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jpAgregarEscLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jtmask, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpAgregarEscLayout.createSequentialGroup()
                        .addComponent(jtcapalm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel11)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpAgregarEscLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpAgregarEscLayout.createSequentialGroup()
                        .addGroup(jpAgregarEscLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btHDD)
                            .addComponent(btSSD))
                        .addGap(26, 26, 26)
                        .addComponent(btGraphics))
                    .addGroup(jpAgregarEscLayout.createSequentialGroup()
                        .addGap(0, 29, Short.MAX_VALUE)
                        .addGroup(jpAgregarEscLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jthostname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jpAgregarEscLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtram, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btagregarEsc)
                .addGap(18, 18, 18))
        );

        tabs.addTab("Agregar PC de Escritorio", jpAgregarEsc);

        jLabel12.setText("IP");

        jLabel13.setText("Mask");

        jLabel14.setText("Hostname");

        jLabel15.setText("Marca");

        jLabel6.setText("Definicion de pantalla");

        rgbbox.setText("Teclado con RGB");

        agregarLaptop.setBackground(new java.awt.Color(102, 255, 102));
        agregarLaptop.setText("Agregar");
        agregarLaptop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarLaptopActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AgregarLaptopLayout = new javax.swing.GroupLayout(AgregarLaptop);
        AgregarLaptop.setLayout(AgregarLaptopLayout);
        AgregarLaptopLayout.setHorizontalGroup(
            AgregarLaptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AgregarLaptopLayout.createSequentialGroup()
                .addGroup(AgregarLaptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AgregarLaptopLayout.createSequentialGroup()
                        .addGroup(AgregarLaptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(AgregarLaptopLayout.createSequentialGroup()
                                .addGroup(AgregarLaptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(AgregarLaptopLayout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addComponent(jLabel12))
                                    .addGroup(AgregarLaptopLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jLabel13)))
                                .addGap(19, 19, 19)
                                .addGroup(AgregarLaptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtIP2, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                                    .addComponent(jtmask2)))
                            .addGroup(AgregarLaptopLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel14)
                                .addGap(18, 18, 18)
                                .addComponent(jthostname2, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(AgregarLaptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AgregarLaptopLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(43, 43, 43)
                                .addComponent(jtmarca, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6)
                            .addComponent(rgbbox)
                            .addComponent(jtdefinicion, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(AgregarLaptopLayout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(agregarLaptop)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        AgregarLaptopLayout.setVerticalGroup(
            AgregarLaptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AgregarLaptopLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(AgregarLaptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jtIP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(jtmarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(AgregarLaptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AgregarLaptopLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(AgregarLaptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jtmask2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AgregarLaptopLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtdefinicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)))
                .addGroup(AgregarLaptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addGroup(AgregarLaptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jthostname2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(rgbbox)))
                .addGap(43, 43, 43)
                .addComponent(agregarLaptop)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        tabs.addTab("Agregar Laptop", AgregarLaptop);

        listPC.setColumns(20);
        listPC.setRows(5);
        jScrollPane1.setViewportView(listPC);

        javax.swing.GroupLayout jpListarLayout = new javax.swing.GroupLayout(jpListar);
        jpListar.setLayout(jpListarLayout);
        jpListarLayout.setHorizontalGroup(
            jpListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpListarLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jpListarLayout.setVerticalGroup(
            jpListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpListarLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        tabs.addTab("Listar", jpListar);

        jpEliminar.setMinimumSize(new java.awt.Dimension(423, 335));

        javax.swing.GroupLayout jpEliminarLayout = new javax.swing.GroupLayout(jpEliminar);
        jpEliminar.setLayout(jpEliminarLayout);
        jpEliminarLayout.setHorizontalGroup(
            jpEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 437, Short.MAX_VALUE)
        );
        jpEliminarLayout.setVerticalGroup(
            jpEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 335, Short.MAX_VALUE)
        );

        tabs.addTab("Eliminar", jpEliminar);

        crudSalir.setBackground(new java.awt.Color(255, 51, 51));
        crudSalir.setText("Salir");
        crudSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crudSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpcrudLayout = new javax.swing.GroupLayout(jpcrud);
        jpcrud.setLayout(jpcrudLayout);
        jpcrudLayout.setHorizontalGroup(
            jpcrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpcrudLayout.createSequentialGroup()
                .addGroup(jpcrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpcrudLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(crudSalir))
                    .addGroup(jpcrudLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jpcrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(tabs, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 51, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpcrudLayout.setVerticalGroup(
            jpcrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpcrudLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tabs, javax.swing.GroupLayout.PREFERRED_SIZE, 321, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(crudSalir)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout frameCrudLayout = new javax.swing.GroupLayout(frameCrud.getContentPane());
        frameCrud.getContentPane().setLayout(frameCrudLayout);
        frameCrudLayout.setHorizontalGroup(
            frameCrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpcrud, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        frameCrudLayout.setVerticalGroup(
            frameCrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpcrud, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        bgPanel.setBackground(new java.awt.Color(102, 102, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Menu Principal");

        btcrud.setText("CRUD PC");
        btcrud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcrudActionPerformed(evt);
            }
        });

        btingrese.setText("Ingresar a PC");

        javax.swing.GroupLayout bgPanelLayout = new javax.swing.GroupLayout(bgPanel);
        bgPanel.setLayout(bgPanelLayout);
        bgPanelLayout.setHorizontalGroup(
            bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgPanelLayout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addGroup(bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btcrud)
                    .addComponent(btingrese)
                    .addComponent(jLabel1))
                .addContainerGap(139, Short.MAX_VALUE))
        );
        bgPanelLayout.setVerticalGroup(
            bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgPanelLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addComponent(btcrud)
                .addGap(51, 51, 51)
                .addComponent(btingrese)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btcrudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcrudActionPerformed
        frameCrud.setVisible(true);
        frameCrud.pack();
    }//GEN-LAST:event_btcrudActionPerformed

    private void crudSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crudSalirActionPerformed
        frameCrud.setVisible(false);
    }//GEN-LAST:event_crudSalirActionPerformed

    private void btHDDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHDDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btHDDActionPerformed

    private void btagregarEscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btagregarEscActionPerformed
        String ip = jtIP.getText();
        String mask = jtmask.getText();
        String host = jthostname.getText();
        int ram = Integer.parseInt(jtram.getText());
        int capAlm = Integer.parseInt(jtcapalm.getText());
        String tipo = "";
        if(btHDD.isSelected()){
            tipo = "HDD";
        }else if(btSSD.isSelected()){
            tipo = "SSD";
        }
        boolean tarjeta = btGraphics.isSelected();
        
        PC_Escritorio pc = new PC_Escritorio(ram,capAlm,tipo,tarjeta,ip,mask,host);
        computadoras.add(pc);
    }//GEN-LAST:event_btagregarEscActionPerformed

    private void agregarLaptopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarLaptopActionPerformed
        String ip = jtIP.getText();
        String mask = jtmask.getText();
        String host = jthostname.getText();
        String marca = jtmarca.getText();
        String def = jtdefinicion.getText();
        boolean rgb = rgbbox.isSelected();
        
        Laptop laptop = new Laptop(marca,def,rgb,ip,mask,host);
        computadoras.add(laptop);
    }//GEN-LAST:event_agregarLaptopActionPerformed

    private void tabsStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tabsStateChanged
        if (tabs.getSelectedIndex() == 1) {
            listPC.setText("");
            for (PC c : computadoras) {
                listPC.append(""+computadoras.indexOf(c) + ".- "+c + "\n");
            }
        }
    }//GEN-LAST:event_tabsStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AgregarLaptop;
    private javax.swing.JButton agregarLaptop;
    private javax.swing.ButtonGroup almacenamiento;
    private javax.swing.JPanel bgPanel;
    private javax.swing.JCheckBox btGraphics;
    private javax.swing.JRadioButton btHDD;
    private javax.swing.JRadioButton btSSD;
    private javax.swing.JButton btagregarEsc;
    private javax.swing.JButton btcrud;
    private javax.swing.JButton btingrese;
    private javax.swing.JButton crudSalir;
    private javax.swing.JFrame frameCrud;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpAgregarEsc;
    private javax.swing.JPanel jpEliminar;
    private javax.swing.JPanel jpListar;
    private javax.swing.JPanel jpcrud;
    private javax.swing.JTextField jtIP;
    private javax.swing.JTextField jtIP2;
    private javax.swing.JTextField jtcapalm;
    private javax.swing.JTextField jtdefinicion;
    private javax.swing.JTextField jthostname;
    private javax.swing.JTextField jthostname2;
    private javax.swing.JTextField jtmarca;
    private javax.swing.JTextField jtmask;
    private javax.swing.JTextField jtmask2;
    private javax.swing.JTextField jtram;
    private javax.swing.JTextArea listPC;
    private javax.swing.JCheckBox rgbbox;
    private javax.swing.JTabbedPane tabs;
    // End of variables declaration//GEN-END:variables
    ArrayList<PC> computadoras = new ArrayList();
}

